#Application infos
info:
  app:
    name: person
    description: Service...
    version: 1.0.0

#Server related configurations
server:
  port: 8080

#Logging related configurations
logging:
  pattern:
    console: '%d{"yyyy-MM-dd''T''HH:mm:ss.SSSZ"} person service-person - %clr(%-4level) %X{token:--} %X{metricName:--} %X{metricValue:--} "%msg"%n'
  level:
    root: error

#Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include: 'info'
      base-path: '/'

springfox:
  documentation:
    swagger:
      v2:
        path:
          /api-docs

spring:
  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:etp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa
      data: classpath:/db-console/init-script.sql
  h2:
      console:
        enabled: true
        path: /db-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop